# Stub file for mechanisms.figures

from matplotlib.figure import Figure

def generate_pie_chart(
    data: list[int],
    labels: list[str],
    colors: list[str],
    fig_width: int = ...,
    fig_height: int = ...,
) -> Figure: ...
def encode_figure_to_base64(fig: Figure) -> str: ...
def get_mechanism_chart(
    mechanism_id: int, fig_width: int = ..., fig_height: int = ...
) -> tuple[Figure, str]: ...
def get_overall_chart(
    project_id: int, fig_width: int = ..., fig_height: int = ...
) -> tuple[Figure, str]: ...
