# Stub file for core.utils.roles
from enum import Enum

class ProjectRole(str, Enum): ...

ROLE_DISPLAY_NAMES: dict[str, str]
ROLE_COLORS: dict[str, str]

def get_role_display(role_value: str) -> str: ...
def get_role_color(role_value: str) -> str: ...
def get_role_choices() -> list[tuple[str, str]]: ...
def get_responsibility_choices() -> list[tuple[str, str]]: ...
def get_role_from_responsibility(responsibility: str) -> str | None: ...
def get_responsibility_from_role(role: str) -> str | None: ...
def get_responsibility_display_name(responsibility: str) -> str: ...
